# Generated by Django 5.0.1 on 2026-06-21 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resume_filename', models.CharField(max_length=255)),
                ('job_description', models.TextField()),
                ('match_score', models.FloatField()),
                ('matched_skills', models.JSONField(default=list)),
                ('missing_skills', models.JSONField(default=list)),
                ('improvement_suggestions', models.JSONField(default=list)),
                ('interview_questions', models.JSONField(default=list)),
                ('full_analysis', models.TextField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
